In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### 產生兩個矩陣然後相加

In [2]:
m1=np.random.randint(1,20,size=(5,5))
m2=np.random.randint(1,20,size=(5,5))

def matrix_plus(m1,m2):
    print(m1)
    print(m2)
    print('相加:' )
    print(m1+m2)

In [3]:
matrix_plus(m1,m2)

[[15  4  1 13 12]
 [ 8  6  7 12 12]
 [16  6  9 16  8]
 [ 7 16 19  3 15]
 [ 9 18 13 18 15]]
[[17  5  8 14 10]
 [14 18  4 12 12]
 [ 3 12 19  7  2]
 [ 8 11  5 11  1]
 [11 13 11 12  9]]
相加:
[[32  9  9 27 22]
 [22 24 11 24 24]
 [19 18 28 23 10]
 [15 27 24 14 16]
 [20 31 24 30 24]]
