In [4]:
### Bubble Sort
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [5]:
scores=np.random.randint(1,50,size=5)

for i in range(len(scores)):
    for j in range(len(scores)):
         if scores[i]<scores[j]:
            scores[i],scores[j]=scores[j],scores[i]
            print(scores)  

[30 46 39 31 38]
[30 39 46 31 38]
[30 31 46 39 38]
[30 31 39 46 38]
[30 31 38 46 39]
[30 31 38 39 46]
