In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

### 有A,B,C三個班級，每班皆有10個學生，期中考結束後，老師希望計算各班級每位學生的加權平均成績。
 
#請隨機產生3個班級的成績單,每班10人,共五科,權重為weights=[0.25,0.25,0.25,0.15,0.10]。
請算出班級加權平均成績，並以一個array輸出。

In [2]:
A=np.random.randint(101,size=(10,5))
B=np.random.randint(101,size=(10,5))
C=np.random.randint(101,size=(10,5))

print('class_A\n',A)
print('class_B\n',B)
print('class_C\n',C)

class_A
 [[82 49 19 55 88]
 [ 9 63 40 76 30]
 [11 96 29 63 83]
 [96 78 50 79 82]
 [45 47 89  9 17]
 [52  0 60 57  0]
 [93 66 28 78 32]
 [46 78  1 15 27]
 [11  2 50  4 76]
 [88 43 93  4 84]]
class_B
 [[88 26 99 92 75]
 [52 39 70 90 54]
 [41 13 13 32 56]
 [45 95 16 59  3]
 [ 3 75 31  2 62]
 [33 37 44  8 97]
 [87 23 61 27 62]
 [11 69 79 99 55]
 [16 96 58 55 10]
 [83 92 16 46 66]]
class_C
 [[ 47  74  50  85  85]
 [ 79  47  65  74  41]
 [ 79  18  10 100  13]
 [  1   2  73   7  52]
 [ 67  48  49  98  27]
 [ 72  76  68  79  51]
 [ 33  38  38  64  19]
 [ 80  24  31  49  89]
 [ 33  55  21  40  40]
 [ 89  85  46  37  58]]


In [3]:
weights=np.array([0.25,0.25,0.25,0.15,0.10])

In [4]:
A1=np.dot(A,weights)
B1=np.dot(B,weights)
C1=np.dot(C,weights)

print("A班平均:",A1)
print("B班平均:",B1)
print("C班平均:",C1)

A班平均: [54.55 42.4  51.75 76.05 48.3  36.55 61.65 36.2  23.95 65.  ]
B班平均: [74.55 59.15 27.15 48.15 33.75 39.4  53.   60.1  51.75 61.25]
C班平均: [64.   62.95 43.05 25.25 58.4  70.95 38.75 50.   37.25 66.35]
